### ISSUE TITLE
link typo

### ISSUE THREAD

**Issue by aaelony** [uncomplicate/neanderthal#10]
The link http://neanderthal.uncomplicate.org/articles/getting_started.html  contains a link `(from the Clojars)` that is slightly wrong and results in page not found. 

`http://neanderthal.uncomplicate.org/articles/clojars.org/uncomplicate/neanderthal`  should be `https://clojars.org/uncomplicate/neanderthal` I believe... Please verify.

Thanks... -A

**Comment by blueberry** [comment]
Will be fixed in the next push. Thanx.
