### ISSUE TITLE
CUDA is not available on macOS from version 11 and up

### ISSUE THREAD

**Issue by blueberry** [uncomplicate/neanderthal#100]
Stack trace from the attempt to load the library as a resource:

```
java.io.IOException: No resource found with name '/lib/libJCudaRuntime-11.0.0-apple-x86_64.dylib'
etc.
```

This is not a bug. CUDA is not available on macOS any more, due to Apple/Nvidia hostility.

The solution is to explicitly exclude all dependencies related to CUDA.

For example, add something like this in your project.clj to globally exclude JCuda jars:

```
:exclusions [org.jcuda/jcuda
                    org.jcuda/jcublas]

```

**Comment by blueberry** [comment]
Please see the updated hello world project.clj.  These exclusions have to be added:

```
:exclusions [[org.jcuda/jcuda-natives :classifier "apple-x86_64"]
               [org.jcuda/jcublas-natives :classifier "apple-x86_64"]]
```

**Comment by HLevering** [comment]
On Mac with M1 Arm chip you have to leave out the classifier or change the classifier to "linux-aarch64" otherwise it will complain on not finding these packages at first repl start.
```
Could not find artifact org.jcuda:jcuda-natives:jar:linux-aarch64:11.4.1 in central (https://repo1.maven.org/maven2/)
Could not find artifact org.jcuda:jcuda-natives:jar:linux-aarch64:11.4.1 in clojars (https://repo.clojars.org/)
Could not find artifact org.jcuda:jcublas-natives:jar:linux-aarch64:11.4.1 in central (https://repo1.maven.org/maven2/)
Could not find artifact org.jcuda:jcublas-natives:jar:linux-aarch64:11.4.1 in clojars (https://repo.clojars.org/)
```
