### ISSUE TITLE
Solver with sv or sv! having issues

### ISSUE THREAD

**Issue by goroda** [uncomplicate/neanderthal#111]
I am having issue working with the solver capabilities. The BLAS functions are working (matrix-vector and matrix-matrix multiplication), but the LAPACK functions (such as sv) seem to be having issues. 

For instance, when I run the following example from one of the blog posts

```
(let [a (dge 3 3 [1 0 1 1 -1 1 3 1 4])
      b (dge 3 4 [11 -2 9 3 -2 1 4 5 -6 -1 0 1])]
  (sv a b))
```

I obtain the following error 

`1. Unhandled java.lang.IllegalAccessError
   class uncomplicate.commons.core$eval8675$fn__8676 (in unnamed
   module @0x3ef3387f) cannot access class jdk.internal.ref.Cleaner
   (in module java.base) because module java.base does not export
   jdk.internal.ref to unnamed module @0x3ef3387f`

My namespace import was
```
(ns stuff.core
  (:require [uncomplicate.fluokitten.core :refer [fmap! fold] :as flu]
            [uncomplicate.neanderthal
             [native :refer [dge dv]]
             ;; [real :refer :all]
             [core :refer [mm mv]]
             [linalg :refer [sv sv! lse]]]))
```

I am running 
- MacOS Mojave 10.14.6
- Clojure version 1.10.1
- Java info 
  java version "10.0.2" 2018-07-17
 Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
 Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
- I installed intel MKL based on the instructions from the [Getting started](https://neanderthal.uncomplicate.org/articles/getting_started.html#requirements) page 
- Running cider on emacs
- Using lein with the following dependencies and exclusions

```
  :dependencies [[org.clojure/clojure "1.10.1"]
                 [uncomplicate/fluokitten "0.9.1"]
                 [uncomplicate/neanderthal "0.39.0"]
                 ]
;; Nvidia doesn't ship CUDA for macOS; you have to add this to your project  
  :exclusions [[org.jcuda/jcuda-natives :classifier "apple-x86_64"]
               [org.jcuda/jcublas-natives :classifier "apple-x86_64"]]
  ;; If on Java 9+, you have to uncomment the following JVM option.
  :jvm-opts ^:replace [#_"--add-opens=java.base/jdk.internal.ref=ALL-UNNAMED"]
  :repl-options {:init-ns gordo-prob.core})
```

Thanks in advance!

**Comment by blueberry** [comment]
You are running on Java 9 or higher, so you have to read this comment and apply it accordingly.
 ;; If on Java 9+, you have to uncomment the following JVM option.
  :jvm-opts ^:replace [#_"--add-opens=java.base/jdk.internal.ref=ALL-UNNAMED"]

**Comment by goroda** [comment]
thank you, thank worked
