### ISSUE TITLE
Mismatch between Neanderthal version; and neanderthal version in examples

### ISSUE THREAD

**Issue by erikmagic** [uncomplicate/neanderthal#113]
Hello Mr. Djuric,
There is a mismatch between your current Neanderthal version and the one specified as a dependencies in your example. 

https://github.com/uncomplicate/neanderthal/blob/d7f683cab829a401420e03b52869d953341377f0/examples/hello-world/project.clj#L5 (should now be 0.41). The same mismatch is true in the benchmarks.

This is problematic when one tries to use CUDA given the complex mapping of clojurecuda and Cuda versions.

Thank you for your work,

Erik

**Comment by blueberry** [comment]
Fixed.
