### ISSUE TITLE
Running numerical-linear-algebra-for-programmers 1.0.0 without CUDA

### ISSUE THREAD

**Issue by maku-no-heya** [uncomplicate/neanderthal#124]
Hi Dragan,
I bought your brilliant NLAFP book with the source code and have a 2019 MacBook Pro with the following specs:
- CPU: 2.8 GHz Quad-Core Intel i7
- RAM: 16GB 2133 MHz LPDDR3
- GPU: Intel Iris Plus Graphics 655 1636MB

I do not have Nvidia hardware, but I'd like to run your examples as efficiently as I can. Your example code currently does not compile because of the dependency on CUDA.

What configuration do you recommend for my hardware (perhaps OpenCL?) and do you have an example or version of the NLAFP code that uses an alternative compute configuration?

Many thanks in advance.

**Comment by jsa-aerial** [comment]
You don't say specifically what the error is, but this may be the issue with jcuda and newer OSX.  Apple being Apple, they keep breaking things (gratuitously IMO).  You should have these exclusions in your project deps:

[[org.jcuda/jcuda-natives :classifier "apple-x86_64"]
 [org.jcuda/jcublas-natives :classifier "apple-x86_64"]]]

**Comment by maku-no-heya** [comment]
Thanks so much, Dragan. I will close this issue, read the appendix, and figure it out. I've resolved this kind of stuff many times before. You and @jsa-aerial have given me some great tips.
I hope you are well and I appreciate your brilliant books and libraries.

-Maku
