### ISSUE TITLE
Not able to run native tests of neanderthal sucessfull

### ISSUE THREAD

**Issue by behrica** [uncomplicate/neanderthal#127]
While we discussed
https://github.com/uncomplicate/deep-diamond/issues/15
the issue that Neanderthal does not find any more the libmkl_rt.so (even when globaly installed) came up as an other issue.

I prepared a Dockerfile which exposed the issue, maybe useful.

```
# failing with
# Execution error (UnsatisfiedLinkError) at java.lang.ClassLoader$NativeLibrary/load0 (ClassLoader.java:-2).
#/tmp/libneanderthal-mkl-0.33.07653633467081296505.so: libmkl_rt.so: cannot open shared object file: No such file or directory

FROM clojure:lein-2.9.8-focal
RUN apt-get update && apt-get -y install git wget python3
RUN wget https://registrationcenter-download.intel.com/akdlm/irc_nas/18721/l_onemkl_p_2022.1.0.223.sh
RUN sh ./l_onemkl_p_2022.1.0.223.sh -a --silent  --eula accept

RUN git clone https://github.com/uncomplicate/neanderthal.git

WORKDIR /tmp/neanderthal
RUN git checkout e01511ff47605f2e4031d58899b303e4435d58e3
RUN lein test uncomplicate.neanderthal.mkl-test
```

**Comment by behrica** [comment]
So it seems to me that **neither** with **lastet** global MKL nor **latest** `[org.bytedeco/mkl-platform-redist "] ` neanderthal native is working.

**Comment by behrica** [comment]
Using older `bytedeco`   (as documented here:  https://neanderthal.uncomplicate.org/articles/getting_started.html=
 (but keeping MKL globally installed) fails with an othe errror)

```
# failing with
# actual result:
# clojure.lang.ExceptionInfo: LAPACK error. {:bad-argument 5, :error-code -5}
#  uncomplicate.neanderthal.internal.host.mkl.FloatSYEngine.copy(mkl.clj:2065)

FROM clojure:lein-2.9.8-focal
RUN apt-get update && apt-get -y install git wget python3
RUN wget https://registrationcenter-download.intel.com/akdlm/irc_nas/18721/l_onemkl_p_2022.1.0.223.sh
RUN sh ./l_onemkl_p_2022.1.0.223.sh -a --silent  --eula accept

RUN git clone https://github.com/uncomplicate/neanderthal.git

WORKDIR /tmp/neanderthal
RUN git checkout e01511ff47605f2e4031d58899b303e4435d58e3

CMD  ["lein", "update-in" ,":dependencies", "conj" ,"[org.bytedeco/mkl-platform-redist \"2020.3-1.5.4\"]" ,"--", "test" ,"uncomplicate.neanderthal.mkl-test" ]
```

-->

```
actual result did not agree with the checking function.
Actual result:
clojure.lang.ExceptionInfo: LAPACK error. {:bad-argument 5, :error-code -5}
  uncomplicate.neanderthal.internal.host.mkl.FloatSYEngine.copy(mkl.clj:2065)
  uncomplicate.neanderthal.internal.host.buffer_block.RealUploMatrix.host(buffer_block.clj:1243)

```

**Comment by behrica** [comment]
Same without MKL installed:

```
# failing with
# actual result:
# clojure.lang.ExceptionInfo: LAPACK error. {:bad-argument 5, :error-code -5}
#  uncomplicate.neanderthal.internal.host.mkl.FloatSYEngine.copy(mkl.clj:2065)

FROM clojure:lein-2.9.8-focal
RUN apt-get update && apt-get -y install git wget python3

RUN git clone https://github.com/uncomplicate/neanderthal.git

WORKDIR /tmp/neanderthal
RUN git checkout e01511ff47605f2e4031d58899b303e4435d58e3

CMD  ["lein", "update-in" ,":dependencies", "conj" ,"[org.bytedeco/mkl-platform-redist \"2020.3-1.5.4\"]" ,"--", "test" ,"uncomplicate.neanderthal.mkl-test" ]
```

**Comment by behrica** [comment]
Doing this, finds the libmkl_rt.so , but it fails on something else, see in comment.

```
# failing with
#Actual result did not agree with the checking function.
#Actual result:
#clojure.lang.ExceptionInfo: LAPACK error. {:bad-argument 5, :error-code -5}
#  uncomplicate.neanderthal.internal.host.mkl.FloatSYEngine.copy(mkl.clj:2065)


FROM clojure:lein-2.9.8-focal
RUN apt-get update && apt-get -y install git wget python3
#RUN wget https://registrationcenter-download.intel.com/akdlm/irc_nas/18721/l_onemkl_p_2022.1.0.223.sh
RUN wget https://registrationcenter-download.intel.com/akdlm/irc_nas/18483/l_onemkl_p_2022.0.2.136.sh
RUN sh ./l_onemkl_p_2022.0.2.136.sh -a --silent  --eula accept

RUN git clone https://github.com/uncomplicate/neanderthal.git

WORKDIR /tmp/neanderthal
RUN git checkout e01511ff47605f2e4031d58899b303e4435d58e3

ENV LD_LIBRARY_PATH="/opt/intel/oneapi/mkl/2022.0.2/lib/intel64"
CMD [ "lein", "update-in", ":dependencies" ,"conj", "[org.bytedeco/mkl-platform-redist \"2022.0-1.5.7\"]", "--", "test", "uncomplicate.neanderthal.mkl-test" ]
```

**Comment by behrica** [comment]
If I do not use "bytedeco", I get an other error:

```
# failing with
#java: symbol lookup error: /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_thread.so.2: undefined symbol: omp_get_num_procs
#Tests failed.


FROM clojure:lein-2.9.8-focal
RUN apt-get update && apt-get -y install git wget python3
#RUN wget https://registrationcenter-download.intel.com/akdlm/irc_nas/18721/l_onemkl_p_2022.1.0.223.sh
RUN wget https://registrationcenter-download.intel.com/akdlm/irc_nas/18483/l_onemkl_p_2022.0.2.136.sh
RUN sh ./l_onemkl_p_2022.0.2.136.sh -a --silent  --eula accept

RUN git clone https://github.com/uncomplicate/neanderthal.git

WORKDIR /tmp/neanderthal
RUN git checkout e01511ff47605f2e4031d58899b303e4435d58e3

ENV LD_LIBRARY_PATH="/opt/intel/oneapi/mkl/2022.0.2/lib/intel64"
CMD [ "lein", "test", "uncomplicate.neanderthal.mkl-test" ]
```

**Comment by behrica** [comment]
I give up at this point in time.
I cannot find a setup of MKL, "org.bytedeco/mkl-platform-redist" and config following the instructions which makes the neanderthal tests pass in "native".
So I am wondering what setup the people here are using.

Probably some "old" setup, which "today" cannot be re-created anymore. (as library versions are gone)

**Comment by blueberry** [comment]
It seems to me that the MKL distribution misses `libiomp5.so`, or you have a wrong iomp5 installation when you set up that manually? Please see the mention of that lib in https://neanderthal.uncomplicate.org/articles/getting_started.html.

This should and usually is automatically in the right place, but it might be broken in some installations, as people create countless variations.

**Comment by behrica** [comment]
Ok, I finally found a working solution, in teh form of a Dockerfile:

```
FROM clojure:lein-2.9.8-focal
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install git wget python3 intel-mkl

RUN git clone https://github.com/uncomplicate/neanderthal.git

WORKDIR /tmp/neanderthal
RUN git checkout e01511ff47605f2e4031d58899b303e4435d58e3

CMD [ "lein", "test", "uncomplicate.neanderthal.mkl-test" ]
```

Very simple, even.

**Comment by behrica** [comment]
But it is not true, in my view, as the instructions here suggest, 
that no mkl installation is needed, when adding the "bytedeco"

---
Add a MKL distribution jar [org.bytedeco/mkl-platform-redist "2020.3-1.5.4"] as your project’s dependency.

Neanderhtal will use the native CPU MKL binaries from that jar automatically, so you don’t need to do anything else
---

This does fail:

```
FROM clojure:lein-2.9.8-focal
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install git

RUN git clone https://github.com/uncomplicate/neanderthal.git

WORKDIR /tmp/neanderthal
RUN git checkout e01511ff47605f2e4031d58899b303e4435d58e3

CMD [ "lein", "update-in", ":dependencies" ,"conj", "[org.bytedeco/mkl-platform-redist \"2020.3-1.5.4\"]", "--", "test", "uncomplicate.neanderthal.mkl-test" ]
```

with 

```
Actual result:
clojure.lang.ExceptionInfo: LAPACK error. {:bad-argument 5, :error-code -5}
  uncomplicate.neanderthal.internal.host.mkl.FloatSYEngine.copy(mkl.clj:2065)
  uncomplicate.neanderthal.internal.host.buffer_block.RealUploMatrix.host(buffer_block.clj:124
  ```
  
So I would  say it requires "a lot of luck", if adding   "[org.bytedeco/mkl-platform-redist "2020.3-1.5.4"]" and "doing nothing else" is indeed working.

**Comment by behrica** [comment]
One way to address this is to try to maintain a single Docker image for the Clojure Data Science community.
I do this in some form here:
https://github.com/behrica/clj-py-r-template/blob/master/docker-base/Dockerfile

It is setup to allow the R and python bindings to Clojure to work out of the box.

I know that the Clojure community is not a very big fan of Docker based development, but maybe it is worth to extend the above docker image to explicitly support neanderthal and therefore deep diamond out of the box.

What to do you think ?

I could give it a go and try to setup all needed stuff for `deep-diamond` in there as well.

**Comment by jsa-aerial** [comment]
@behrica Hi Carsten, I have the needed MKL libs for Linux, Mac, and Win that I created for installation for Saite. They are all in compressed archives.  These have always worked for me across various machines, and OS versions (only Intel Mac - no new Arm stuff) and Win10 for Windows.  For Linux and (Intel) Mac, [aerosaite](https://github.com/jsa-aerial/aerosaite), the self installing uberjar variant, comes with scripts for running it that setup the paths for the MKL.  This too, has always worked for various users.  Aerosaite automatically downloads and installs the MKL libs to a local directory relative to the .saite home directory.  BUT, you could manually grab these if you wish and install them in some similar location that makes sense for you.

[Linux](http://bioinformatics.bc.edu/~jsa/linux-mkl-libs.tar.gz)
[Mac](http://bioinformatics.bc.edu/~jsa/mac-mkl-libs.tar.gz)
[Win](http://bioinformatics.bc.edu/~jsa/win-mkl-libs.tar.gz)

I am unsure about how to automatically set the path for Win (someone recently gave me an idea of what it should be so maybe the next release the Win scripts will have that as well).

I'm not sure if your setup is 'special' in some way that would keep this from working, but it may be worth a try.  As I say, this has always worked.  The scripts are in the resources folder at the aerosaite github (link above).

**Comment by blueberry** [comment]
Hi @jsa-aerial that is really helpful. Maybe we can make this or some more focused standalone version of this official recommendation for people that for some reason or another can't make the official binaries work on their system?

**Comment by blueberry** [comment]
Just a quick note: Neanderthal's MKL dependency does not need any installation other than the lib files being in any location where the appropriate OS looks fir shared libraries. Even copy/paste works.

**Comment by behrica** [comment]
@jsa-aerial  I do agree that we should have more "instructions" / variants to get MKL installed (and deep-diamond working)
I "nearly" managed to extend the polyglot Dockerfile to have all working:
With "all" I mean deep-diamond running in a Dockercontainer supporting "native = MKL", "CUDA GPL" and "OpenCL GPU".

"Working" I measure by have the all deep-diamond tests passing.

Even for non Docker users, reading teh Dockerfile can be usefull:
See last sections here: 
https://github.com/behrica/clj-py-r-template/blob/master/docker-base/Dockerfile

It is nearly working...
I dived very deep into the issues, and tried a lot of different things.

It would be very helpful, if somebody woth more knowledge on CUDA / OpenCL / Linux would have a look.

The dockerfile can be build as usual with `docker build .`  and run on (hopefully) any machine with a GPU,
as  `docker run --gpus all -w /tmp/deep-diamond    <imgae-id>    lein test`

Currently I get this error, and I am not sure what to try next.
```
Execution error (UnsatisfiedLinkError) at java.lang.ClassLoader$NativeLibrary/load0 (ClassLoader.java:-2).
/root/.javacpp/cache/opencl-3.0-1.5.7-linux-x86_64.jar/org/bytedeco/opencl/linux-x86_64/libjniOpenCL.so: /usr/lib/x86_64-linux-gnu/libOpenCL.so: version `OPENCL_2.2' not found (required by /root/.javacpp/cache/opencl-3.0-1.5.7-linux-x86_64.jar/org/bytedeco/opencl/linux-x86_64/libjniOpenCL.so)
```

Could somebody help out with this ?

**Comment by behrica** [comment]
As you see in the Dockerfile I settled on Cuda 11.4, with 11.6 I had even more weiredd issues and did not come "this far".

**Comment by behrica** [comment]
> Just a quick note: Neanderthal's MKL dependency does not need any installation other than the lib files being in any location where the appropriate OS looks for shared libraries. Even copy/paste works.

The question is "which precise shared libraries" it needs. It seems to me, that given on how MKL is installed, "different libraries" do get installed in the appropriate places. And I had issues with wrong GLIBC versions and so on.

**Comment by behrica** [comment]
I would advocate a Docker solution, as "out-of-the-box" and the quickest route to "try deep-diamond".
(at least for the Linux users with Docker ...)

**Comment by behrica** [comment]
> @behrica Hi Carsten, I have the needed MKL libs for Linux, Mac, and Win that I created for installation for Saite. They are all in compressed archives. These have always worked for me across various machines, and OS versions (only Intel Mac - no new Arm stuff) and Win10 for Windows. For Linux and (Intel) Mac, [aerosaite](https://github.com/jsa-aerial/aerosaite), the self installing uberjar variant, comes with scripts for running it that setup the paths for the MKL. This too, has always worked for various users. Aerosaite automatically downloads and installs the MKL libs to a local directory relative to the .saite home directory. BUT, you could manually grab these if you wish and install them in some similar location that makes sense for you.
> 
> [Linux](http://bioinformatics.bc.edu/~jsa/linux-mkl-libs.tar.gz) [Mac](http://bioinformatics.bc.edu/~jsa/mac-mkl-libs.tar.gz) [Win](http://bioinformatics.bc.edu/~jsa/win-mkl-libs.tar.gz)
> 
Interesting approach. In my Dockerfile, I do the other pathway.
I download and run the official installers in "silent mode".

As we are in a fixed environment (Fixed OS in Docker container), this should as well always work.

**Comment by behrica** [comment]
Usualy I put as well a Dockerimage in Dockerhub,
so this would be the most "out-of-the-box" working solution.

the idea of the Dockercontainer is to expose a Clojure nREPL on a given port, to which you can connect to from Cider / Calva or whatever nREPL client.

This works nicely as well on a remote machine, tunneling the nREPL port via ssh.
Given how Clojure works, it is often not needed to have the source files on the remote machine / Docker, but depends what the code does. 

Setting this "file sync" up is the most complicated part, but supported and documented in other places.

**Comment by blueberry** [comment]
> @jsa-aerial I do agree that we should have more "instructions" / variants to get MKL installed (and deep-diamond working) I "nearly" managed to extend the polyglot Dockerfile to have all working: With "all" I mean deep-diamond running in a Dockercontainer supporting "native = MKL", "CUDA GPL" and "OpenCL GPU".
> 
> "Working" I measure by have the all deep-diamond tests passing.
> 
> Even for non Docker users, reading the Dockerfile can be useful: See last sections here: https://github.com/behrica/clj-py-r-template/blob/master/docker-base/Dockerfile
> 
> It is nearly working... I dived very deep into the issues, and tried a lot of different things.
> 
> It would be very helpful, if somebody with more knowledge on CUDA / OpenCL / Linux would have a look.
> 
> The dockerfile can be build as usual with `docker build .` and run on (hopefully) any machine with a GPU, as `docker run --gpus all -w /tmp/deep-diamond <imgae-id> lein test`
> 
> Currently I get this error, and I am not sure what to try next.
> 
> ```
> Execution error (UnsatisfiedLinkError) at java.lang.ClassLoader$NativeLibrary/load0 (ClassLoader.java:-2).
> /root/.javacpp/cache/opencl-3.0-1.5.7-linux-x86_64.jar/org/bytedeco/opencl/linux-x86_64/libjniOpenCL.so: /usr/lib/x86_64-linux-gnu/libOpenCL.so: version `OPENCL_2.2' not found (required by /root/.javacpp/cache/opencl-3.0-1.5.7-linux-x86_64.jar/org/bytedeco/opencl/linux-x86_64/libjniOpenCL.so)
> ```
> 
> Could somebody help out with this ?

OpenCL platform loader has to be present on the system if you want to use opencl with Neanderthal. Please note that deep diamond only supports dense layers for OpenCL via a general Neanderthal engine. Please see ClojureCL documentation for details

**Comment by behrica** [comment]
What do you mean by "OpenCL platform loader has to be present " ?
I have "clinfo" installed, if this is what you mean. And it runs and tells me something about my openCL driver, I believe:

```
Number of platforms                               1
  Platform Name                                   NVIDIA CUDA
  Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 3.0 CUDA 11.6.110
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_icd cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_nv_kernel_attribute cl_khr_device_uuid cl_khr_pci_bus_info cl_khr_external_semaphore cl_khr_external_memory cl_khr_external_semaphore_opaque_fd cl_khr_external_memory_opaque_fd
  Platform Host timer resolution                  0ns
  Platform Extensions function suffix             NV

  Platform Name                                   NVIDIA CUDA
Number of devices                                 1
  Device Name                                     Tesla P40
  Device Vendor                                   NVIDIA Corporation
  Device Vendor ID                                0x10de
  Device Version                                  OpenCL 3.0 CUDA
  Driver Version                                  510.54
  Device OpenCL C Version                         OpenCL C 1.2
  Device Type                                     GPU
  Device Topology (NV)                            PCI-E, 00:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               30
  Max clock frequency                             1531MHz
  Compute Capability (NV)                         6.1
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x64
  Max work group size                             1024


....
.....
ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1
        NOTE:   your OpenCL library only supports OpenCL 2.1,
                but some installed platforms support OpenCL 3.0.
                Programs using 3.0 features may crash
                or behave unexpectedly
```

Does this mean that "OpenCL is not support on my GPU / Driver". It seems to say that I have OpenCL 2.1, while I need 2.2.
But the card support 3.0 ....
Is this correct ?

Sorry, complete newbie on OpenCL.

**Comment by blueberry** [comment]
This means your setup should be ok. Your only implementation is nvidia, which supports Opencl 1.2. OpenCL is basically 1.2 repackaged, And Opencl 2 has most features, but is left as a vestige as Nvidia and Apple sabotaged it. Complicated, I know...

**Comment by behrica** [comment]
Thanks, that helps.
So what can I do about:

```
Execution error (UnsatisfiedLinkError) at java.lang.ClassLoader$NativeLibrary/load0 (ClassLoader.java:-2).
/root/.javacpp/cache/opencl-3.0-1.5.7-linux-x86_64.jar/org/bytedeco/opencl/linux-x86_64/libjniOpenCL.so: /usr/lib/x86_64-linux-gnu/libOpenCL.so: version `OPENCL_2.2' not found (required by /root/.javacpp/cache/opencl-3.0-1.5.7-linux-x86_64.jar/org/bytedeco/opencl/linux-x86_64/libjniOpenCL.so)
```
It happens during "lein test", I suppose during the tests which are using OpenCL.
So "somthing" is still wrong in my setup, I guess.

So I assume correctly that "opencl-3.0-1.5.7"   requires "openCL  3.0" (or at least more then 2.1)
The dependency to it comes from `deep-diamond`

**Comment by behrica** [comment]
My Dockerimage is an Ubuntu 20.04 image. So it **is** Ubuntu in most regards.

I would like to promote usage of 'neanderthal', but the installation of it (or better said it's dependencies MKL and CUDA / OpenCL) are a gigantic hurdle.
I consider myself a very experienced Java / Clojure / Linux / Docker user but I have no idea what I am doing here to get it work.

I am thinking somehow as well, that 'Docker' is the only way out, but that is not shared by lots of people, unfortunately.

I think that "maintaining and publishing"  a Dockerfile and Image with a "working deep-diamond" where the user only need to type "docker run --gpus all xxxx" is important in this.

I thought I can do this on my own, but I think this is not the case. I know too little on  CUDA, OpenCL and "extending Java with native code" in order to bring this forward myself.

The installation instructions are too general to allow me to further work on the Dockerfile efficiently.

**Comment by behrica** [comment]
I propose to go a step back, and I work on a "Minimal" Dockerfile (ubuntu based) which has only the goal to setup MKL, Cuda, OpenCL to get the "neanderthal" test suite working inside of it.

Maybe I could contribute that Dockerfile to the "neanderthal" GitHub. I am not sure, if I can get it "working" by myself, but maybe we could collaborate on it in some form.

At least by "reviewing" it and trying to see, if I do something which cannot work. What do you think ?
Are you interested in supporting this, even when you are not a Docker user yourself.

**Comment by jsa-aerial** [comment]
> Hi @jsa-aerial that is really helpful. Maybe we can make this or some more focused standalone version of this an official recommendation for people that for some reason or another can't make the official vendor binaries work on their system?

That sounds like a reasonable/good idea.  Suggestion on how to proceed?

**Comment by blueberry** [comment]
I'm not familiar with how saite works, so I don't know precisely, but is there a way to provide the basic MKL and/or CUDA distribution without other parts of saite and even without Neanderthal?

Anyway, it might be a good option for people who can't or don't want to follow my official guides to have the scripts you provide as an option, and if it works sufficiently predictable, we can link to your repository as and option from the getting started guide.

The only drawback I see is that it would make users read these guide even less, and it would appear more complicated.
I'm specifically referring to this:

>I would like to promote usage of 'neanderthal', but the installation of it (or better said it's dependencies MKL and CUDA / >OpenCL) are a gigantic hurdle.
>I consider myself a very experienced Java / Clojure / Linux / Docker user but I have no idea what I am doing here to get it work.

Perhaps if I have written: the user *has* to copy these 7 *.so* files at folder X, and *must* add this folder to LD_LIBRARY_PATH, and *must* restart shell, it would have been simpler. Instead, I opted to write a more versatile guide with all popular option, and users being impatient get lost in the sea of options...

**Comment by behrica** [comment]
> > I would advocate a Docker solution, as "out-of-the-box" and the quickest route to "try deep-diamond". (at least for the Linux users with Docker ...)
> 
> Frankly, if you want just works automatically "out of the box", aerosaite is the quickest and easiest route. Certainly for Linux users this is pretty much guaranteed to work. For CPU.
> 
> I think you are being naive about putting something together for automatic GPU use. There you are up against all the issues about getting the GPU usable completely aside from Neanderthal/DeepDiamond. There are just way too many variations, requirements and dependencies.

This could be. But is this even true when using Docker ?  Have you tried it ? Or does Docker at least help ?
I am not convinced, that it is "not possible" to at least make one single Dockerimage which just works most of the time.
But yes, similar to aerosaite.

Or at least that Dockerfile can be "parametrized" (so not assuming one fixed one for every situation, but a template)

So that the Dockerfile is at least a "base or template" which then a user can modify , which is hopefully easier then "installing from scratch"

**Comment by jsa-aerial** [comment]
> This could be. But is this even true when using Docker ? 

Of course it is true using Docker - Docker is some  magic thing that somehow automatically knows what type (vendor, model, version) GPU, how many, and what the drivers are and if they are properly installed.

You'd have to have a Docker image for all the combinations

Myself, I don't much like Docker, but understand those who do...

**Comment by behrica** [comment]
> > This could be. But is this even true when using Docker ?
> 
> Of course it is true using Docker - Docker is _not_ some magic thing that somehow automatically knows what type (vendor, model, version) GPU, how many, and what the drivers are and if they are properly installed.
> 
Agree, but I would hope that over time all vendors will produce "one driver", which work for all their GPUs.
The we could have a parameterized Dockerfile, which just gets the "vendor".
And from inside Docker I can even "read" what GPU I have, and could make decisions accordingly what to install.

So I still think that only a "view people maintain a Dockerfile" needed to know all nifty details, while the majority of user could just "use" the Docker file or image.

Similar to the JVM abstraction.

**Comment by blueberry** [comment]
> "pip install tensorflow-gpu"

As far as I know, pip install tensorflow-gpu does not install cuda, it *expects cuda to be available on your system*. Exactly as Neanderthal. But the difference is that Neanderthal will throw an exception if you call absent cuda backend, while tensorflow might automatically fall back to the default engine, whatever it is?

OTOH, conda does (AFAIK) install CUDA, but an internal one. I could do that, if you comit to my (hypothetical) proprietary environment such is conda. You still have to make sure that the right GPU drivers are present.

**Comment by behrica** [comment]
Thanks , ClojureCUDA docu says currently this, which seems to say "any CUDA 11.x"

```
Minimum requirements
Java 8
CUDA Toolkit 11.0 (prefer 11.4)
Linux or Windows. macOS doesn’t allow CUDA from version 11 and up. You can only use an old release of ClojureCUDA on macOS.
```

I hope I help with this comments, if not let me know...

**Comment by blueberry** [comment]
I updated the docs of ClojureCUDA to clarify this.

You might use any CUDA version with ClojureCUDA. However, if the CUDA version on your system does not match the one that ClojureCUDA depends on in project.clj, you have to specify explicit dependency to the matching JCuda version in YOUR project.clj

It's similar for Neanderthal, but it might be that a very outdated CUDA does not support all features that I use, and break at will.

Ditto for DD, but I don't expect old CUDA versions so work successfully.

**Comment by blueberry** [comment]
As far as I can see, your system has CUDA 11.6.1, which is exactly what is expected, so you should not change any default. 11.4.1 generally shouldn't work on your machine (or if it does, it's more luck than anything else).

**Comment by behrica** [comment]
yeah, one reason for me to insist in Docker is "multiple computers".
I use GPU on Azure Cloud VMS, and I would like to avoid to "configure each of them individually".
They are kind of "temporary resources".
But I understood know better the "precise matching requirement", thanks for clarification.

**Comment by behrica** [comment]
yes, It is about that. Took me a while to figure it out,

**Comment by blueberry** [comment]
Fortunately, you can help solve it. That would require that you build JCuda on your (older) system, and these binaries will then work on newer systems too!

Please check out this issue:
https://github.com/jcuda/jcuda-main/issues/51

**Comment by behrica** [comment]
I created PR #128 
with a minimal example Docker setup. So for me we can close this issue here.
