### ISSUE TITLE
Using opencl on mac os x using Jogamp

### ISSUE THREAD

**Issue by ashishnegi** [uncomplicate/neanderthal#13]
Hello Thanks for the great work.
I am trying to load opencl on Mac OS X in repl. As stated in documentation, i am getting errors for missing : `java.lang.NullPointerException: No resource found with name '/lib/libJOCL_0_2_0-apple-x86_64.dylib'`

If i understand correctly, the solution would be to build latest : https://github.com/gpu/JOCL on Mac. 
I tried but seemed to hit some roadblocks.

I found that jocl jars for mac osx are available at : `http://jogamp.org/deployment/webstart-next/archive/jogamp-all-platforms.7z`

How much would it be possible to switch between different OpenCl bindings ?

**Comment by blueberry** [comment]
jogamp and jocl are completely different, and jogamp supports only old opencl, so they are not compatible at all.

**Comment by ashishnegi** [comment]
I guess i have to make JOCL work on mac.. :)

**Comment by blueberry** [comment]
@ashishnegi One of the next releases (maybe even the next one) will work on mac out of the box. And another good news, Neanderthal GPU engine will also work on Mac. I already implemented it, I am waiting for the release of a dependency, which will probably happen in the following weeks.
