### ISSUE TITLE
Typo in error structure

### ISSUE THREAD

**Issue by quoll** [uncomplicate/neanderthal#133]
Not actually a bug, but the two structures describing the state when throwing an exception has a typo of `:stirde-mult` rather than `:stride-mult`

https://github.com/uncomplicate/neanderthal/blob/e4a03ddca20261bf7718b7bcabc66e7ef48ee072/src/clojure/uncomplicate/neanderthal/core.clj#L207
https://github.com/uncomplicate/neanderthal/blob/e4a03ddca20261bf7718b7bcabc66e7ef48ee072/src/clojure/uncomplicate/neanderthal/core.clj#L297

**Comment by blueberry** [comment]
Thanks. Fixed.
