### ISSUE TITLE
uncomplicate.neanderthal.native takes a long time to load

### ISSUE THREAD

**Issue by agriffis** [uncomplicate/neanderthal#135]
Hi! I'm very new to neanderthal and the JVM, so I apologize if this should be obvious.

```
$ time clj -e "(require 'uncomplicate.neanderthal.native)"

real    0m20.972s
user    0m36.498s
sys     0m0.803s
```

Is it expected that loading this module would take 20 seconds?

This is on Fedora with

```
openjdk version "23.0.1" 2024-10-15
OpenJDK Runtime Environment (build 23.0.1+11-39)
OpenJDK 64-Bit Server VM (build 23.0.1+11-39, mixed mode, sharing)
```

and

```edn
{:deps {uncomplicate/neanderthal {:mvn/version "0.49.2"}
        org.bytedeco/mkl$linux-x86_64-redist {:mvn/version "2024.0-1.5.10"}}}
```

If this is unexpected, do you have any suggestions for what I should check? Thanks!

**Comment by blueberry** [comment]
You can try running a minimal JavaCPP MKL project, and see how much that does take on your machine. If it's something close to what you got here, then I guess MKL just takes lots of time to be unpacked from javacpp's jar and loaded on the Java classpath, so there's nothing Neanderthal can do about it. If that happen to be much faster, then we can investigate further.

**Comment by agriffis** [comment]
Hmm, this is an i7 with 32G memory. I can't imagine it's that much undersized compared to what other people are using, but certainly it's a good test.

I agree that loading mkl is likely the underlying problem, but this test loads in under a second:

```
✸ time clj -e "(import 'org.bytedeco.javacpp.DoublePointer)"
org.bytedeco.javacpp.DoublePointer

real    0m0.873s
user    0m1.569s
sys     0m0.196s
```

Do you have a pointer to a minimal JavaCPP MKL project that I should try? Nothing pops up instantly when I google.

**Comment by blueberry** [comment]
But you are not loading MKL at all there, you're only creating a double pointer (try the double-pointer function from the clojure-cpp and it will certainly load in the ballpark).

As for the minimal JavaCPP MKL project, try at github....javacpp-presets/mkl.

**Comment by agriffis** [comment]
Thanks for the pointer. I'm stumbling around the javacpp-presets repo trying to figure it out.

In the meantime, I think my original question is valid. Is 20s expected? How long does it take on your machine? If it takes 5s on your machine, for example, then I can imagine that 20s is "reasonable" from the perspective that it takes a while to unpack the jar, and my machine is just a bit old.

**Comment by blueberry** [comment]
I believe that the 20s on your machine is reasonable.

**Comment by agriffis** [comment]
Okay, thanks. Just curious, how long does it take for you?

**Comment by blueberry** [comment]
It's already available in the snapshots, but you'll have to build several projects yourself (which is fairly easy; just use lein install for each).
