### ISSUE TITLE
Print of a CSRMatrix fails

### ISSUE THREAD

**Issue by kolstae** [uncomplicate/neanderthal#136]
Execute `(uncomplicate.neanderthal.sparse/csr uncomplicate.neanderthal.native/native-float 1 70 [[10 20 30 40] nil])` in REPL fails with:
`Error printing return value (MissingFormatArgumentException) at java.util.Formatter/format (Formatter.java:2790).
Format specifier '%s'`

**Comment by blueberry** [comment]
Fixed in 0.50.1.

**Comment by kolstae** [comment]
Wow! That's incredible
