### ISSUE TITLE
Core dump with scal!

### ISSUE THREAD

**Issue by mikera** [uncomplicate/neanderthal#19]
I get a core dump on Windows using Neanderthal when executing the following:

```clojure
(core/scal! 1 (core/create-vector cblas/cblas-double (range 5)))
```

Not sufficiently familiar with Neanderthal internals to understand what is causing this. Any ideas?

Without calling `scal!` the vector seems to be constructed just fine, it is definitely the `scal!` that is causing the core dump.

```
#
#  EXCEPTION_ILLEGAL_INSTRUCTION (0xc000001d) at pc=0x000000006830ee78, pid=8632, tid=952
#
# JRE version: Java(TM) SE Runtime Environment (8.0_40-b26) (build 1.8.0_40-b26)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [neanderthal-atlas-0.3.18978921121746295551.dll+0xee78]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Mike\git\neanderthal\hs_err_pid8632.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by blueberry** [comment]
Does the hello world example work on your machine?

**Comment by mikera** [comment]
Also fails. I think anything that is hitting BLAS is failing?

**Comment by blueberry** [comment]
Have you installed atlas and put libatlas.dll somewhere on the path?

**Comment by mikera** [comment]
I was under the impression that you had build Neanderthal 0.8.0 with native library support included. Is that not the case?

**Comment by blueberry** [comment]
Yes, I have. Please read the guide.
