### ISSUE TITLE
Support primitive array transfer

### ISSUE THREAD

**Issue by MrOerni** [uncomplicate/neanderthal#25]
By now, only native matrices/vectors and clojure seqs are supported. 

I have a large primitive array (81m ints). If I transfer this to a clojure seq (and therefore use boxed Objects) I'll use a lot of memory. This doesn't have to be since one can easily put the array directly into the internal ByteBuffer.

**Comment by blueberry** [comment]
Implemented this and many more variants in the latest commit.
