### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by veerapatyok** [uncomplicate/neanderthal#28]
I try to run cuda example code with [this link](http://dragan.rocks/articles/17/CUDA-and-cuBLAS-GPU-matrices-in-Clojure) and I have error is

` java.lang.UnsatisfiedLinkError: /tmp/libneanderthal-mkl-0.14.02129154059413193959.so: libmkl_rt.so: cannot open shared object file: No such file or directory, compiling:(uncomplicate/neanderthal/internal/host/mkl.clj:102:5)`

my ubuntu installed cuda with version 7.5

**Comment by blueberry** [comment]
You are missing Intel MKL library files. Read Neanderthal Getting Started guide http://neanderthal.uncomplicate.org/articles/getting_started.html

**Comment by veerapatyok** [comment]
I installed intel mkl but the same error show again

**Comment by blueberry** [comment]
Check whether you added the appropriate directories on the LD_LIBRARY_PATH.

That's the only thing that comes to my mind with the information you provided. If that does not work, please write a detailed description of steps that you did, and the info that you got at each step.

**Comment by veerapatyok** [comment]
after install mkl

- I checked mkl with [this link](https://software.intel.com/en-us/mkl-linux-developer-guide-checking-your-installation)
- run mklvars.sh
- export LD_LIBRARY_PATH=/opt/intel/mkl/lib/intel64:/opt/intel/lib/intel64:$LD_LIBRARY_PATH

**Comment by blueberry** [comment]
Where did you perform the export, and have you made sure that the export is permanent? If you did that in the terminal, it is valid only for the current session in this terminal, and your clojure/jvm does not see that. If that is the case, either do that export permanently, or start your clojure repl from the same shell session.

See about `/etc/ld.so.conf.d/` on ubuntu: https://stackoverflow.com/questions/35046753/using-mkl-error-while-loading-shared-libraries-libmkl-intel-lp64-so

Of course, neanderthal does not care how you provide those *.so files, so you can even copy the files that are needed to `/usr/lib`

This might help you find your way with that:

**Comment by veerapatyok** [comment]
it have other error `Could not initialize native OpenCL library. Implementation library could not be loaded` but I use cuda

**Comment by blueberry** [comment]
Good news is that Neanderthal works for you. Bad news is that Neanderthal's CUDA engine requires hardware with at least SM 3.0 architecture, while your card is SM 2.1.
