### ISSUE TITLE
Unable to run benchmarks in Q4 2017

### ISSUE THREAD

**Issue by MageMasher** [uncomplicate/neanderthal#36]
I was unable to execute the benchmarking code because I was unable to find `mikera.matrixx`, `mikera.matrixx.algo` anywhere ( not even a github repo ).

 Should we consider removing it?

**Comment by blueberry** [comment]
These are parts of the Vectorz library, which was the default implementation of core.matrix at the time. I have just checked, and it is still in https://github.com/uncomplicate/neanderthal/blob/master/examples/benchmarks/project.clj, as it should.

What error are you getting when you try to run the benchmarks?

**Comment by MageMasher** [comment]
I was attempting to reproduce the results in my own new project, but I just ran from the example project and it worked. Sorry for the confusion, I'll close this out.
