### ISSUE TITLE
Cannot find jcuda jars

### ISSUE THREAD

**Issue by prismofeverything** [uncomplicate/neanderthal#43]
Hello,

I tried the simplest thing, adding this line to my `project.clj` from a fresh `lein new`:

    [uncomplicate/neanderthal "0.18.0"]

Then tried to run `lein repl` and got this error:

    Could not find artifact org.jcuda:jcuda-natives:jar:apple-x86_64:0.9.0 in central (https://repo1.maven.org/maven2/)
    Could not find artifact org.jcuda:jcuda-natives:jar:apple-x86_64:0.9.0 in clojars (https://clojars.org/repo/)
    Could not find artifact org.jcuda:jcublas-natives:jar:apple-x86_64:0.9.0 in central (https://repo1.maven.org/maven2/)
    Could not find artifact org.jcuda:jcublas-natives:jar:apple-x86_64:0.9.0 in clojars (https://clojars.org/repo/)

What's up? Are there references to jars that don't exist? I thought I may need to add the `clojurecuda` dep as well (as mentioned by the Getting Started page) so I added this line as well:

    [uncomplicate/clojurecuda "0.3.0"]

but I get the same error. Any ideas? On MacOSX 10.11.6.

**Comment by blueberry** [comment]
@prismofeverything Due to some bug in Clojars, I couldn't make this automatic in Neanderhal (for now), so I added the example of how to use this workaround in the Hello World project. See https://github.com/uncomplicate/neanderthal/blob/master/examples/hello-world/project.clj

**Comment by blueberry** [comment]
Neanderthal 0.24.0 will fix this macos issue by shipping with macos binaries.
