### ISSUE TITLE
Unable to use without CUDA

### ISSUE THREAD

**Issue by mattrepl** [uncomplicate/neanderthal#48]
I'm trying to use neanderthal for the first time on my laptop which does not have a discrete GPU. Neanderthal's Getting Started page implies CUDA cruft is not required to use neanderthal, but when I start up a REPL with the current release of neanderthal included as a lein project dependency I get errors similar to:

> Could not find artifact org.jcuda:jcuda-natives:jar:apple-x86_64:0.9.2

Do I need to follow the installation instructions for GPU support even though it's not something I can even use? My laptop is a 13" MacBook Pro w/ Intel Iris.

Thanks for any help.

**Comment by blueberry** [comment]
Youll find the answer to this isue in the Getting started guide.

**Comment by mattrepl** [comment]
The installation section on the Getting Started page:

>Installation

>1. Add Neanderthal jars to your classpath (from the Clojars).
2. To use the native engine: install Intel’s MKL on your system following Native Engine Requirements).
3. To use the GPU engine: install the drivers and a CUDA and/or OpenCL platform software provided by the vendor of your graphic card (you probably already have that; see GPU Engine Requirements).

I followed the installation instructions for using the native engine. Does neanderthal require I install dependencies for the GPU engine even if I am not using it?

**Comment by blueberry** [comment]
It looks to me the same as #41 and #43. Also, start with the provided hello world project.

**Comment by mattrepl** [comment]
Ah, thanks. I didn’t think to check closed issues.

**Comment by blueberry** [comment]
Neanderthal 0.24.0 will fix this macos issue by shipping with macos binaries.
