### ISSUE TITLE
Error after Version Update

### ISSUE THREAD

**Issue by rfinz** [uncomplicate/neanderthal#63]
UPGRADE PATH:
Recording here in case anyone else has a similar issues.

Updating from 0.22.1 to 0.25.1 my installation printed this error (when the REPL is started):
```
Intel MKL FATAL ERROR: cannot load libmkl_vml_avx2.dylib or libmkl_vml_mc.dylib.
Subprocess failed
```
and refused to start. Reverted to 0.22.1 and everything still seemed to be working.

I copied `libmkl_vml_avx2.dylib` and `libmkl_vml_mc.dylib` into `/usr/local/lib` and this fixed the problem for 0.25.1 (documentation doesn't mention these files but does mention that there may be specific files for different intel architectures).

I also had to update any namespace references to "aux" since it was migrated to "auxil".

This is all on a laptop:

macOS Mojave
Version 10.14.3
MacBook Pro (15-inch, 2017)
Processor 2.8 GHz Intel Core i7
Memory 16 GB 2133 MHz LPDDR3
Startup Disk Macintosh HD
Graphics Radeon Pro 555 2048 MB
Intel HD Graphics 630 1536 MB

**Comment by blueberry** [comment]
Thank you for the report, rfinz. The `aux` to `auxil` rename was required to fix a windows bug - windows doesn't allow a file to be named `aux`...
