### ISSUE TITLE
request for svd example

### ISSUE THREAD

**Issue by aaelony** [uncomplicate/neanderthal#8]
Could you provide an example of SVD using neanderthal?  

Thanks,
Avram

**Comment by blueberry** [comment]
Currently neanderthal does not implement decompositions (those features will be added in the future), so you'd have to write your own procedure using blas functions. Do you have an exact algorithm (in any notation) that you want to use, or you are asking whether there is a ready-made function for that (not yet)?

**Comment by aaelony** [comment]
Was mainly curious as I didn't see anything in the API just yet, but was hoping for a ready-made function. Thanks for your response, looks promising. -A

**Comment by blueberry** [comment]
Just stumbled on this issue. I think it would be useful to point out that SVD (and many other lapack functions) has been available available since 0.9.0.
