### ISSUE TITLE
Why is mrows the number of rows and ncols the number of cols, shouldn't it be nrows?

### ISSUE THREAD

**Issue by vascoferreira25** [uncomplicate/neanderthal#89]
Hi,
I've been fiddling with neanderthal for fun and I came across the `mrows` function in `core` that returns the number of rows of a matrix. There is a function called `ncols` that returns the number of columns.

Wouldn't it be better, for better consistency, to call this function `nrows`?

**Comment by blueberry** [comment]
It's because matrix dimensions are usually m x n, so m-rows and n-cols help users distinguish better between these two. It is easy (or at least easier) to mix up nrows and ncols, or to forget to edit your code properly if you switch the orientation. In other words, just an useful mnemonic device.
