### ISSUE TITLE
Build failing on Windows

### ISSUE THREAD

**Issue by mikera** [uncomplicate/neanderthal#9]
When trying either `lein test` or `lein midje` on Windows I get the following error:

```
C:\Users\Mike\git\neanderthal>lein test
java.lang.IllegalArgumentException: Bad artifact coordinates uncomplicate:neanderthal-atlas:jar:amd64-Windows 8.1-gpp-jni:0.1.0, expected format is <groupId>:<artifactId>[:<extension>[:<classifier>]]:<version>
 at org.sonatype.aether.util.artifact.DefaultArtifact.<init> (DefaultArtifact.java:73)
    org.sonatype.aether.util.artifact.DefaultArtifact.<init> (DefaultArtifact.java:56)
    cemerick.pomegranate.aether$artifact.invoke (aether.clj:222)
    cemerick.pomegranate.aether$dependency.invoke (aether.clj:230)
    cemerick.pomegranate.aether$resolve_dependencies_STAR_$fn__190.invoke (aether.clj:708)
    clojure.core$map$fn__4553.invoke (core.clj:2624)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.PersistentVector.create (PersistentVector.java:68)
    clojure.lang.LazilyPersistentVector.create (LazilyPersistentVector.java:30)
    clojure.core$vec.invoke (core.clj:361)
    cemerick.pomegranate.aether$resolve_dependencies_STAR_.doInvoke (aether.clj:701)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:630)
    cemerick.pomegranate.aether$resolve_dependencies.doInvoke (aether.clj:729)
    clojure.lang.RestFn.invoke (RestFn.java:2088)
    leiningen.core.classpath/fn (classpath.clj:115)
.... etc .....
```

**Comment by blueberry** [comment]
Neanderthal uses midje, so it is lein midje instead of lein test.

**Comment by mikera** [comment]
Ah yes I see. Doesn't seem to change the issue: `lein midje` produces the same exception.

**Comment by blueberry** [comment]
1. Do you have ATLAS on your machine?

**Comment by mikera** [comment]
I've tried installing Altlas but I don't think that is the problem: the above error looks like a dependency resolution issue to me.

**Comment by blueberry** [comment]
Trust me, If atlas is not available, it won't work. The first step is to have atlas there.

**Comment by mikera** [comment]
The problem seems to be this (or the non-existence thereof):
`uncomplicate:neanderthal-atlas:jar:amd64-Windows 8.1-gpp-jni:0.1.0`

Is there a way to build this?

**Comment by blueberry** [comment]
Yes. It is neanderthal-atlas project https://github.com/uncomplicate/neanderthal-atlas. You need to compile THAT library with atlas on Windows. There is an automated build script there, that might need minor tweaks, depending on the tools available on your OS. I am sorry the build process is not polished (yet) on Windows to the level of mvn install - it would have been if I had a Windows copy, but I hope the community will solve that.

**Comment by blueberry** [comment]
As of version 0.8.0, neanderthal will come with a pre-compiled windows binary.
