### ISSUE TITLE
Why is the source in GE matrices column-oriented by default?

### ISSUE THREAD

**Issue by vascoferreira25** [uncomplicate/neanderthal#90]
Hi, why is it that when you specify a source for a GE matrix, it is by default column-oriented?

For example:

```clojure
(dge [[1 2 3]
      [4 5 6]])

;; => #RealGEMatrix[double, mxn:3x2, layout:column, offset:0]
;;    ▥        ↓       ↓       ┓    
;;    →       1.00    4.00         
;;    →       2.00    5.00         
;;    →       3.00    6.00         
;;     ┗                       ┛    
```

I know that if I specify the rows, columns and the layout it will stay as it should, but I don't understand why.

```clojure
(dge 2 3 [[1 2 3]
          [4 5 6]] {:layout :row})

;; => #RealGEMatrix[double, mxn:2x3, layout:row, offset:0]
;;    ▤       ↓       ↓       ↓       ┓    
;;    →       1.00    2.00    3.00         
;;    →       4.00    5.00    6.00         
;;     ┗                               ┛    
```

**Comment by blueberry** [comment]
Because something has to be default, and it is the column layout, which is also default in Fortran, and in lots of other data analysis software because (statistical) variables are usually represented by columns.
