### ISSUE TITLE
Installation in FreeBSD?

### ISSUE THREAD

**Issue by lungsi** [uncomplicate/neanderthal#96]
Hi,
I was just curious if anybody here has successfully installed Intel-MKL in BSD systems and hence installed Neanderthal?

Since intel-mkl comes in the flavor of Windows, MacOS and Linux I installed the `.rpm` in Linuxulator mode of FreeBSD, passed the library path to the system environment variable but I can't get Neanderthal to work. I even tried some of the approaches in MacOS installation but to no avail.

Regards,
Lungsi

PS: Currently the intel-mkl is not available as the freebsd port.

**Comment by blueberry** [comment]
I don't know. Anyway, the solution is in no way related to Neanderthal. If you find any information that would make ordinary C program work with MKL on BSD, that will work with Neanderthal too.

**Comment by atisharma** [comment]
> Currently the intel-mkl is not available as the freebsd port.

@lungsi This is the issue. The only way I can see is to use Neanderthal compiled against another LAPACK.
